### ISSUE TITLE
Error if no options are selected

### ISSUE THREAD

**Issue by zsoltime** [codesect/cs01-team-ada-04#24]
There is an error if a user unticks every option and reloads the page:

<img width="519" alt="Screenshot 2019-11-18 at 11 44 09" src="https://user-images.githubusercontent.com/3144128/69051897-8ae71f80-09fd-11ea-95a9-1fe6d942d6b0.png">

As every option loaded from local storage is false, `generatePassword` throws the error above. We should set the generated password to an empty string if there is an error.

**Comment by Mizou9999** [comment]
fix #24

**Comment by Mizou9999** [comment]
Fix #24

**Comment by zsoltime** [comment]
Fixed by #22
